spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # Connection Pool Settings for Production
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# CORS Configuration for Production (AWS CloudFront/ALB)
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://leetcode-motivation.vercel.app}

  base-url: http://localhost:6084/api

# Health check and metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      cloudwatch:
        enabled: true

# Security headers
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict

  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot