spring:
  application:
    name: LeetcodeMotivation
  mvc:
    log-request-details: true

server:
  port: 6084
  servlet:
    contextPath: /api
  error:
    include-message: always

# Common application properties
payment:
  point:
    value: 10

costs:
  easy-cost: 100
  medium-cost: 300
  hard-cost: 750

rewards:
  items:
    - id: coffee-no-sugar
      title: No Sugar Coffee
      description: Basic black coffee or americano without sugar
      pointCost: 100
      image: /images/regular-coffee.jpg
      category: coffee

    - id: starbucks-latte
      title: Starbucks Latte
      description: Classic Starbucks latte of your choice
      pointCost: 250
      image: /images/paper-cup-starb.png
      category: coffee

    - id: monster-energy-no-sugar
      title: Monster Energy Drink (No Sugar)
      description: Sugar-free Monster energy drink
      pointCost: 300
      image: /images/monster-no-sugar.jpg
      category: energy

    - id: starbucks-frappe
      title: Starbucks Frappe
      description: Refreshing Starbucks frappe or frappuccino
      pointCost: 400
      image: /images/starbucks-frappe.jpg
      category: coffee

    - id: game-wallet-10
      title: Game Wallet $10
      description: $10 credit for Steam, PlayStation, or Xbox
      pointCost: 1000
      image: /images/game-wallet.jpg
      category: gaming
